name: Release Sidekick Agent

on:
  workflow_dispatch:

jobs:
  build_wheels_linux:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    env:
      CIBW_ARCHS_LINUX: x86_64
      CIBW_BUILD: "cp27-* cp36-* cp37-* cp38-* cp39-*"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        env:
          CIBW_BEFORE_ALL: bash build.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_wheels_macos:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest]
        python-version: [3.8]
    env:
      CIBW_ARCHS_MACOS: x86_64
      CIBW_BUILD: "cp27-* cp36-* cp37-* cp38-* cp39-*"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        env:
          CIBW_BEFORE_ALL: bash build.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels_linux, build_wheels_macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: wheelhouse
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.SIDEKICK_PYPI_USERNAME }}
          password: ${{ secrets.SIDEKICK_PYPI_PASSWORD }}
          packages_dir: wheelhouse
